server:
  port: 9000

# server name
spring:
  application:
    name: api-gateway

# eureka path
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


zuul:
  # custom routes mapping
  routes:
    product-service: /apigateway/product/**
    order-service: /apigateway/order/**
  #ignore product-service
  #ignored-services: product-service
  ignored-patterns: /*-service/**
  #handle the problem of empty http request header
  sensitive-headers: