
server:
  port: 8781

# eureka path
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#server name
spring:
  application:
    name: order-service
  redis:
    database: 0
    host: 127.0.0.1
    port: 9736
    timeout: 2000

#custom load balance,default RoundRobinRule,more(to see IRule)
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

#hystrix defualt 1s
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic