spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuwuruoshui/config-cloud-test.git
          username: xuwuruoshui
          password: xxxx
          timeout: 5
          #default git branch is master
          default-label: master

server:
  port: 9100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


